### ISSUE TITLE
fails to piar 

### ISSUE THREAD

**Issue by cab113** [HomeKidd/ESP8266-HomeKit-Contact-Sensor-Elgato-Eve-Door-Window#1]
Hi , this sensor fails to pair have tried 5 times, think the problem lies here 

!! HomeKit: Failed to compact data: sector data read error
!!! HomeKit: Failed to write pairing info to flash: max number of pairings

thanks for the code

log is below

ip:192.168.1.49,mask:255.255.255.0,gw:192.168.1.1
>>> wifi_config: Connected to WiFi network
HomeKid > Starting HomeKit Server
Door state was requested (open).
>>> HomeKit: Starting server
!!! HomeKit: Failed to read flash magic
>>> HomeKit: Formatting flash at 0x100000
!!! HomeKit: Failed to erase flash
>>> HomeKit: Generated new accessory ID: BB:B9:90:BB:BA:7E
!!! HomeKit: Failed to write accessory ID to flash
>>> HomeKit: Generated new accessory key
!!! HomeKit: Failed to write accessory key to flash
>>> HomeKit: Configuring mDNS
mDNS announcement: Name=HomeKid-49D1F1-BBB9 [0B]md=ï£¿ Door[06]pv=1.0[14]id=BB:B9:90:BB:BA:7E[07]c#=4161[04]s#=1[04]ff=0[04]sf=1[05]ci=10[0B]sh=sjQC8w== Port=5556 TTL=4500
>>> HomeKit: Got new client connection: 4
>>> HomeKit: [Client 4] Pair Setup Step 1/3
>>> HomeKit: [Client 4] Pair Setup Step 2/3
>>> HomeKit: [Client 4] Pair Setup Step 3/3
!!! HomeKit: Failed to compact data: sector data read error
!!! HomeKit: Failed to write pairing info to flash: max number of pairings
!!! HomeKit: [Client 4] Failed to store pairing (code -2)
>>> HomeKit: [Client 4] Closing client connection

**Comment by HomeKidd** [comment]
Hi!
Seems to be the  problem is related to the flash size. Which esp8266 did you use and what was to settings that you flash with?
This error comes when you flash the .bin file with wrong settings and the ESP cannot erease the flash 0x100000 for storing the HomeKit settings. 
You should flash the ESP according to the flash size: eg.: Wemos/NodeMCU has 4Mb (4 mega byte ) flash which is 32mbit (megabit). Smaller flash sizes (512kb/4mbit, 1Mb/8mbit, 2MB/16mbit) are not supported because 0x10000 flash sector didnt excist on these ESP8266 boards

**Comment by cab113** [comment]
thank you, managed to pair Node MCU, had to choose 32mb flash size to format 0x100000 successfully.
